package main

import (
	"database/sql"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/d4rthvadr/dusky-go/internal/http/handlers"
	"github.com/d4rthvadr/dusky-go/internal/store"
	swaggerDocs "github.com/d4rthvadr/dusky-go/swagger" // This line is necessary for go-swagger to find the docs package and generate the swagger documentation. The docs package is generated by go-swagger based on the comments in the main.go file and the handlers.
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	httpSwagger "github.com/swaggo/http-swagger"
)

type application struct {
	config  AppConfig
	store   store.Storage
	db      *sql.DB
	handler *handlers.Handler
}

type AppConfig struct {
	addr   string
	apiUrl string
}

func (app *application) mount() *chi.Mux {

	r := chi.NewRouter()
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)
	r.Use(middleware.Recoverer)
	r.Use(middleware.Logger)

	r.Route("/v1", func(r chi.Router) {
		r.Get("/health", app.handler.HealthCheck)

		apiURL := strings.TrimRight(app.config.apiUrl, "/")
		docsUrl := fmt.Sprintf("%s/swagger/doc.json", apiURL)

		r.Get("/swagger/*", httpSwagger.Handler((httpSwagger.URL(docsUrl))))

		r.Route("/posts", func(r chi.Router) {
			r.Post("/", app.handler.CreatePost)

			r.Route("/{postID}", func(r chi.Router) {

				r.Get("/", app.handler.GetPost)
				r.Delete("/", app.handler.DeletePost)
				r.Patch("/", app.handler.UpdatePost)
			})
		})

		r.Route("/users", func(r chi.Router) {
			r.Post("/", app.handler.CreateUser)

			r.Route("/{userID}", func(r chi.Router) {

				r.Use(app.handler.UserContextMiddleware) // this will load the user and add it to the context for all the routes that match /users/{userID}/*
				r.Get("/", app.handler.GetUser)
				r.Put("/follow", app.handler.FollowUser)
				r.Put("/unfollow", app.handler.UnfollowUser)
			})

			r.Group(func(r chi.Router) {
				r.Get("/feed", app.handler.GetUserFeed)
			})
		})

	})

	return r
}

func (app *application) Run(mux *chi.Mux) error {

	// Docs
	swaggerDocs.SwaggerInfo.Title = "Dusky API"
	swaggerDocs.SwaggerInfo.Description = "This is a sample server for a social media application called Dusky. It provides endpoints for managing users, posts, comments, and feeds."
	swaggerDocs.SwaggerInfo.Version = version
	swaggerHost := app.config.addr
	swaggerSchemes := []string{"http"}

	if parsedAPIURL, err := url.Parse(app.config.apiUrl); err == nil {
		if parsedAPIURL.Host != "" {
			swaggerHost = parsedAPIURL.Host
		}

		if parsedAPIURL.Scheme != "" {
			swaggerSchemes = []string{parsedAPIURL.Scheme}
		}
	}

	swaggerDocs.SwaggerInfo.Host = swaggerHost
	swaggerDocs.SwaggerInfo.BasePath = "/v1"
	swaggerDocs.SwaggerInfo.Schemes = swaggerSchemes

	srv := http.Server{
		Addr:         ":" + app.config.addr,
		Handler:      mux,
		WriteTimeout: time.Second * 30,
		ReadTimeout:  time.Second * 15,
		IdleTimeout:  time.Minute,
	}

	log.Printf("server has started at %s", app.config.addr)

	return srv.ListenAndServe()
}

func NewApplication(config AppConfig, store store.Storage, db *sql.DB) *application {
	return &application{config: config, store: store, db: db, handler: handlers.New(store, version)}
}
