name: Audit

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-go@v3
              with:
                  go-version: 1.24.0

            - name: Run gofmt check
              run: test -z "$(gofmt -l .)"

            - name: Generate swagger docs
              run: go run github.com/swaggo/swag/cmd/swag@latest init -g ./cmd/api/main.go -d . -o swagger

            - name: Run go vet
              run: go vet ./...

            - name: Install staticcheck
              run: go install honnef.co/go/tools/cmd/staticcheck@latest

            - name: Run staticcheck
              run: staticcheck ./...

            - name: Run tests
              run: go test -race ./...
